"""add payment fields to orders

Revision ID: 063ed7cea976
Revises: f8d319dc520d
Create Date: 2026-09-25 23:22:18.261847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '063ed7cea976'
down_revision: Union[str, Sequence[str], None] = 'f8d319dc520d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_provider', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('payment_order_id', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('payment_transaction_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'orders', ['payment_transaction_id'])
    op.create_unique_constraint(None, 'orders', ['payment_order_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_column('orders', 'payment_transaction_id')
    op.drop_column('orders', 'payment_order_id')
    op.drop_column('orders', 'payment_provider')
    # ### end Alembic commands ###
